return {
    ["jeep"] = {
        paints = {
            "hill_climber_10th_anniversary_premium","jeep_flames","jeep_graphite",
            "jeep_hue_bronze","jeep_hue_light-blue","jeep_hue_violet","jeep_metal",
            "jeep_checkered_green","jeep_classic","jeep_hue_flames-blue","jeep_hue_rally_brown",
            "jeep_rally","jeep_splash","jeep_checkered","hill_climber_spring_falls_premium",
            "jeep_banana","jeep_blue","jeep_broken_premium","jeep_halloween","jeep_heavy",
            "jeep_hue_green","jeep_kangaroo_premium","jeep_pixel","VIP",
        },
        wheels = {
            "hill_climber_tire-10th_anniversary","jeep_tire-motorcycle","jeep_tire-old",
            "jeep_tire-safari","jeep_tire-simple","jeep_tire-steampunk","jeep_tire-tractor",
            "hill_climber_spring_falls_tire_premium","jeep_tire-hcr","jeep_tire-broken_premium",
            "jeep_tire-goth","jeep_tire-halloween","jeep_tire-heavy","jeep_tire-kangaroo_premium",
            "jeep_tire-pixel","jeep_tire-vip_small",
        },
    },
    ["scooter"] = {
        paints = {
            "scooter_hue_blue-white","scooter_hue_pink-white","black","rock",
            "scooter_pierre_epic","diwali2022_premium","moped","scooter_hue_blue",
            "scooter_hue_red","Web","VIP","yellow",
        },
        wheels = {
            "jeep_tire-vip_small","jeep_tire-motorcycle","jeep_tire-old","jeep_tire-simple",
            "jeep_tire-tractor","tire-pierre","jeep_tire-hcr","scooter_tire-diwali2022_premium",
            "tire-goth","tire-safari","tire-steampunk","tire_moped",
        },
    },
    ["bus"] = {
        paints = {
            "Green","Trio","Cat","Graffiti","London","bus_trophy_epic",
            "bus_bandbus_premium","bus_chicken_premium","bus_nightcrawler_premium",
            "bus_ramen_premium","Flag","Halloween","Luck","Sauna","School","Sleek","VIP",
        },
        wheels = {
            "bus_tire-hcr","bus_tire-motorcycle","bus_tire-old","bus_tire-safari",
            "bus_tire-simple","bus_tire-steampunk","bus_tire-tractor","bus_tire-trophy_epic",
            "bus_default","bus_tire-bandbus_premium","bus_tire-chicken_premium","bus_tire-goth",
            "bus_tire-nightcrawler_premium","bus_tire-ramen_premium","bus_tire-vip_small",
        },
    },
    ["superjeep"] = {
        paints = {
            "superjeep_cubic","superjeep_hue_pink","superjeep_hue_yellow",
            "superjeep_yellowstripe","superjeep_yellowstripe_hue","superjeep_camo",
            "superjeep_camo_hue","superjeep_safari_epic","superjeep_swim_premium",
            "hill_climber_mk2_saltmaker_premium","superjeep_halloween","superjeep_hue_blue",
            "superjeep_hue_green","superjeep_ninja","superjeep_pro","superjeep_superhero",
            "superjeep_xmas","VIP",
        },
        wheels = {
            "jeep_tire-hcr","jeep_tire-motorcycle","jeep_tire-old","jeep_tire-simple",
            "jeep_tire-tractor","superjeep_tire-safari","superjeep_tire-steampunk",
            "superjeep_tire-safari_epic","superjeep_tire-swim_premium",
            "hill_climber_mk2_tire-saltmaker_premium","superjeep_default","superjeep_tire-goth",
            "superjeep_tire-ninja","superjeep_tire-pro","superjeep_tire-vip_big",
            "superjeep_tire-xmas","superjeep_tire_superhero",
        },
    },
    ["tractor"] = {
        paints = {
            "hue_1","hue_2","hue_3","hotrod","hotrod_hue1","orange","dragon",
            "swamp","swamp_hue1","tractor_deepforest_premium","tractor_fire_premium","VIP",
        },
        wheels = {},
    },
    ["motocross"] = {
        paints = {
            "motocross_black-yellow","motocross_black-yellow_hue","motocross_hue_yellow-green",
            "motocross_flames","motocross_flames_hue","motocross_lizard_epic",
            "motocross_explorer_premium","motocross_green","motocross_green_hue",
            "motocross_hue_blue","motocross_hue_red","motocross_hue_yellow",
            "motocross_nikita_acrobat_premium","motocross_nikita_superhero_premium","VIP",
        },
        wheels = {
            "jeep_tire-hcr","jeep_tire-motorcycle","jeep_tire-old","jeep_tire-simple",
            "jeep_tire-tractor","motocross_tire-lizard_epic","jeep_tire-vip_tilted",
            "motocross_tire-explorer_premium","tire-goth","tire-safari","tire-steampunk",
            "motocross_tire-nikita_acrobat_premium","motocross_tire-nikita_superhero_premium",
        },
    },
    ["dunebuggy"] = {
        paints = {
            "dunebuggy_exploder","dunebuggy_princess","dunebuggy_vanilla",
            "dunebuggy_pop_epic","dunebuggy_juice_premium","dunebuggy_moonbuggy",
            "dunebuggy_pumpkin","dunebuggy_racebuggy","dunebuggy_skull_premium",
            "dunebuggy_sunbug","dunebuggy_warlock_premium","dunebuggy_waverider","VIP",
        },
        wheels = {
            "dunebuggy_tire-monster","dunebuggy_tire-old","dunebuggy_tire-pickup",
            "dunebuggy_tire-safari","dunebuggy_tire-tractor","dunebuggy_tire-pop_epic",
            "dunebuggy_default","dunebuggy_tire-juice_premium","dunebuggy_tire-moonbuggy",
            "dunebuggy_tire-ninja","dunebuggy_tire-pimped","dunebuggy_tire-pro",
            "dunebuggy_tire-racebuggy","dunebuggy_tire-skull_premium","dunebuggy_tire-vip_big",
            "dunebuggy_tire-warlock_premium","dunebuggy_tire-waverider","dunebuggy_tire-xmas",
        },
    },
    ["sportscar"] = {
        paints = {
            "arrow","twocoloured","twocoloured_hue","sportscar_moonwalk_epic",
            "sportscar_steampunk_epic","sports_hue_pink","sports_hue_yellow",
            "sportscar_bee_premium","sportscar_drifting_orange_premium",
            "sportscar_drifting_pink_premium","sportscar_flames","sportscar_flames_hue1",
            "sportscar_flames_hue2","sportscar_gloomvale_premium","sportscar_oldie_premium",
            "sportscar_orange","sportscar_snowflake","VIP",
        },
        wheels = {
            "sportscar_tire-hcr","sportscar_tire-motorcycle","sportscar_tire-old",
            "sportscar_tire-safari","sportscar_tire-simple","sportscar_tire-steampunk",
            "sportscar_tire-tractor","sportscar_tire-moonwalk_epic",
            "sportscar_tire-steampunk_epic","sportscar_default","sportscar_tire-bee_premium",
            "sportscar_tire-bundle","sportscar_tire-drifting_orange_premium",
            "sportscar_tire-flames","sportscar_tire-gloomvale_premium","sportscar_tire-goth",
            "sportscar_tire-halloween","sportscar_tire-oldie_premium","sportscar_tire-snowflake",
            "sportscar_tire-drifting_pink_premium","sportscar_tire-vip_small",
        },
    },
    ["monster"] = {
        paints = {
            "fang_hue","fang","flames","monster_hue_blue-flames","monster_donut",
            "monster_steampunk_epic","monster_america","monster_hue_blue","monster_hue_pink",
            "monster_police_premium","monster_survivor","monster_xmas","VIP",
        },
        wheels = {
            "monster_tire-donut","monster_tire-steampunk_epic","monster_default",
            "monster_tire-police_premium","monster_tire-survivor","monster_tire-usa",
            "monster_tire-vip_big","monster_tire-xmas",
        },
    },
    ["upsidedown"] = {
        paints = {
            "hue_default_autumn","hue_default_blue","berry","hue_berry_blue",
            "upsidedown_driftmas2020_premium","upsidedown_enjin_premium",
            "upsidedown_halloween2021_premium","upsidedown_scifi_premium",
            "upsidedown_space_premium","VIP",
        },
        wheels = {
            "upsidedown_tire-berry","upsidedown_default","upsidedown_tire-driftmas2020_premium",
            "upsidedown_tire-enjin_premium","upsidedown_tire-halloween2021_premium",
            "upsidedown_tire-space_premium","upsidedown_tire-vip","upsidedown_tire_scifi_premium",
        },
    },
    ["pickup_truck"] = {
        paints = {
            "oldie","pickup_hue_pink","oldie_hue","pickup_hue_scifi-green","scifi",
            "adventure","giftwrap","nationalday","pickup_heavenride_premium",
            "pickup_hue_green","pickup_icegrille_premium","pimped","sunkenship","VIP",
        },
        wheels = {
            "pickup_tire-hcr","pickup_tire-motorcycle","pickup_tire-old","pickup_tire-safari",
            "pickup_tire-simple","pickup_tire-steampunk","pickup_tire-tractor",
            "pickup_tire-adventure","pickup_tire-heaven_premium","pickup_tire-icegrille-premium",
            "pickup_tire-nationalday","pickup_tire-pimped","pickup_tire-sunkenship",
            "pickup_tire-vip_big",
        },
    },
    ["chopper"] = {
        paints = {
            "hue_blue-b","pink","golden","hue_blue-green","hue_orange-purple",
            "chopper_marina_premium","chopper_survivor_premium","freerider","ghostrider",
            "horse","hue_blue","VIP",
        },
        wheels = {
            "jeep_tire-motorcycle","jeep_tire-old","jeep_tire-simple","jeep_tire-tractor",
            "chopper_tire-horse","chopper_tire-marina_premium","chopper_tire-survivor_premium",
            "chopper_tire_back-ghostrider","chopper_tire_back-vip","tire-goth",
            "tire-safari","tire-steampunk",
        },
    },
    ["minitank"] = {
        paints = {
            "camo_winter","camo_forest","battledamage","M1","tank_hue_blue",
            "tank_hue_green","tank_pineapple_premium","VIP",
        },
        wheels = {},
    },
    ["lowrider"] = {
        paints = {
            "lowrider_blue_common","lowrider_brown_common","lowrider_chrome_common",
            "lowrider_purple_common","lowrider_red_common","lowrider_yellow_common",
            "lowrider_burgundy_rare","lowrider_double_rare","lowrider_emerald_rare",
            "lowrider_pinkstreak_rare","lowrider_red_angles_epic","lowrider_splash_epic",
            "lowrider_flame_premium","lowrider_ghost_premium","lowrider_luxury_premium",
            "lowrider_racer_premium","lowrider_retroride_premium","lowrider_survivor_premium","VIP",
        },
        wheels = {
            "lowrider_tire-red_epic","lowrider_tire-splash_epic",
            "car_tire-lowrider_luxury_premium","lowrider_default","lowrider_tire-flame_premium",
            "lowrider_tire-old-ghost_premium","lowrider_tire-racer_premium",
            "lowrider_tire-retro_premium","lowrider_tire-survivor_premium","lowrider_tire-vip",
        },
    },
    ["snowmobile"] = {
        paints = {
            "Blue","Green","Purple","Red","Orange","Poison","Shark","Water_Splash",
            "Modern","snowmobile_disco_premium","VIP",
        },
        wheels = {},
    },
    ["monowheel"] = {
        paints = {
            "bluestripes","bluestripes_hue_pink","default_hue_green",
            "monowheel_china_premium","monowheel_nautilus_premium",
            "monowheel_voltage_premium","VIP",
        },
        wheels = {
            "monowheel_tire-hcr","monowheel_tire-motorcycle","monowheel_tire-old",
            "monowheel_tire-safari","monowheel_tire-simple","monowheel_tire-steampunk",
            "monowheel_tire-tractor","monowheel_default","monowheel_tire-china_premium",
            "monowheel_tire-goth","monowheel_tire-halloween","monowheel_tire-heavy",
            "monowheel_tire-nautilus_premium","monowheel_tire-vip_small",
            "monowheel_tire-voltage_premium",
        },
    },
    ["beast"] = {
        paints = {
            "beast_brown_common","beast_green_common","beast_pink_common","beast_red_common",
            "beast_teal_common","beast_white_common","beast_yellow_common",
            "beast_rare_bluecheckers","beast_rare_darkgreen","beast_rare_tricolor",
            "beast_rare_whiteflame","beast_rocket_epic","beast_tiger_epic",
            "beast_chimera_premium","beast_driftmas2023_premium","beast_old_premium",
            "beast_sarcophagus_premium","beast_spaceship_premium","VIP",
        },
        wheels = {
            "beast_chimera_premium","beast_default","beast_sarcophagus_premium",
            "beast_spaceship_premium","beast_tire-driftmas2023_premium",
            "beast_tire-old_premium","beast_vip",
        },
    },
    ["rally"] = {
        paints = {
            "rally_hcr","rally_hcraser","rally_star","rally_vord","rally_lash",
            "rally_luxury_epic","china","rally_abstract_premium","rally_bomber_premium",
            "rally_dragonboat_premium","rally_driftmas2021_premium","rally_frank",
            "rally_green","rally_itasha_premium","rally_lava_premium","rally_lion",
            "rally_milk_premium","rally_nikita","rally_samurai_premium","rally_scifi",
            "rally_yellow","rally_zombie","workshop","VIP",
        },
        wheels = {
            "rally_tire-hcr","rally_tire-motorcycle","rally_tire-old","rally_tire-safari",
            "rally_tire-simple","rally_tire-tractor","rally_tire-luxury_epic","rally_default",
            "rally_itasha_tire-premium","rally_tire-abstract_premium","rally_tire-bomber_premium",
            "rally_tire-china","rally_tire-driftmas2021_premium","rally_tire-frank",
            "rally_tire-goth","rally_tire-green","rally_tire-halloween","rally_tire-heavy",
            "rally_tire-milk_premium","rally_tire-nikita","rally_tire-samurai_premium",
            "rally_tire-vip_big","rally_tire_lava_premium","rally_tire_scifi","rally_tire_workshop",
        },
    },
    ["formula"] = {
        paints = {
            "fingersoft","orangewhite","CNY","formula_green","formula_hue_blue",
            "formula_survivor_premium","formula_villain_premium","VIP",
        },
        wheels = {
            "formula_tire-goth","formula_tire-hcr","formula_tire-motorcycle",
            "formula_tire-old","formula_tire-safari","formula_tire-simple",
            "formula_tire-steampunk","formula_tire-tractor","formula_default",
            "formula_tire-bundle","formula_tire-cny","formula_tire-survivor_premium",
            "formula_tire-villain_premium","formula_tire-vip_small",
        },
    },
    ["musclecar"] = {
        paints = {
            "musclecar_blue_common","musclecar_green_common","musclecar_pink_common",
            "musclecar_red_common","musclecar_yellow_common","musclecar_blueflame_rare",
            "musclecar_checker_rare","musclecar_purpleflame_rare","musclecar_yellowgreen_rare",
            "musclecar_bluegreen_epic","musclecar_popart_epic","musclecar_spectrum_epic",
            "musclecar_splash_epic","musclecar_camo_premium","musclecar_derby_premium",
            "musclecar_halloween_premium","musclecar_lucky_premium","musclecar_skully_premium",
            "musclecar_tiger_premium","musclecar_marshal_premium","VIP",
        },
        wheels = {
            "musclecar_tire-hcr","musclecar_tire-motorcycle","musclecar_tire-old",
            "musclecar_tire-safari","musclecar_tire-simple","musclecar_tire-tractor",
            "musclecar_default","musclecar_tire-camo_premium","musclecar_tire-derby_premium",
            "musclecar_tire-goth","musclecar_tire-halloween_premium",
            "musclecar_tire-lucky_premium","musclecar_tire-skully_premium",
            "musclecar_tire-tiger_premium","musclecar_tire-marshal_premium",
            "musclecar_tire-vip",
        },
    },
    ["racing_truck"] = {
        paints = {
            "green","red","cowboy","halloween","jet_engine",
            "racing_truck_amusement_park_premium","racing_truck_cny2021_premium",
            "racing_truck_diwali-2024","VIP",
        },
        wheels = {
            "racing_truck_tire-hcr","racing_truck_tire-monster","racing_truck_tire-old",
            "racing_truck_tire-tractor","racing_truck_tire-amusement_park_premium",
            "racing_truck_tire-cny2021_premium","racing_truck_tire-cowboy",
            "racing_truck_tire-diwali-2024_premium","racing_truck_tire-shiny",
            "racing_truck_tire-vip","racing_truck_tire_halloween",
        },
    },
    ["hotrod"] = {
        paints = {
            "hue_green","hue_pink","hue_purple","flames","flames2","stickers",
            "hotrod_cny2022_premium","hotrod_docshocks_premium","hotrod_heavymetal_mythic",
            "hotrod_illusion_premium","hotrod_mecha_premium","hotrod_modern",
            "hotrod_mummy_premium","hotrod_nikita_premium","hotrod_survivor","VIP",
        },
        wheels = {
            "hotrod_tire-goth","hotrod_tire-hcr","hotrod_tire-motorcycle",
            "hotrod_tire-simple","hotrod_tire-steampunk","hotrod_tire-king",
            "hotrod_default","hotrod_tire-cny2022_premium","hotrod_tire-docshocks_premium",
            "hotrod_tire-heavymetal_mythic","hotrod_tire-mecha_premium",
            "hotrod_tire-mummy_premium","hotrod_tire-new_survivor","hotrod_tire-nikita_premium",
            "hotrod_tire-survivor","hotrod_tire_illusion_premium","hotrod_tire_vip",
        },
    },
    ["electric_car"] = {
        paints = {
            "electric_car_blue_common","electric_car_green_common","electric_car_purple_common",
            "electric_car_red_common","electric_car_yellow_common","electric_car_blueline_rare",
            "electric_car_chevron_rare","electric_car_stripe_rare","electric_car_flames_epic",
            "electric_car_lightning_epic","electric_car_atom_premium",
            "electric_car_bomberman_premium","electric_car_caustic_premium",
            "electric_car_cookie_premium","electric_car_dragonboat_premium",
            "electric_car_robot_premium","electric_car_scifi_premium",
            "electric_car_unicorn_premium","VIP",
        },
        wheels = {
            "electric_car_default","electric_car_tire-atom_premium",
            "electric_car_tire-bomberman_premium","electric_car_tire-caustic_premium",
            "electric_car_tire-cookie_premium","electric_car_tire-robot_premium",
            "electric_car_tire-scifi_premium","electric_car_tire-unicorn_premium",
            "electric_car_tire-vip",
        },
    },
    ["superbike"] = {
        paints = {
            "common_hue_1","common_hue_2","flames","flames_hue1","steampunk",
            "superbike_blue_df_epic","superbike_green_df_epic","superbike_orange_df_epic",
            "falcon","justice_bringer","superbike_enjin_premium","superbike_mitch",
            "superbike_racing_black_premium","superbike_red_premium",
            "superbike_villain_premium","superbike_racing_blue_premium","VIP",
        },
        wheels = {},
    },
    ["lambo"] = {
        paints = {
            "hue_green","hue_pink","hue_purple","orange","red","blackwhite","bluestripes",
            "king","orangewhite","ace","chameleon","CNY2020","lambo_kobra_premium",
            "supercar_knight_premium","supercar_nikita","tattoo","xmas","VIP",
        },
        wheels = {
            "lambo_tire-goth","lambo_tire-hcr","lambo_tire-motorcycle","lambo_tire-simple",
            "lambo_tire-steampunk","lambo_tire-king","lambo_default","lambo_tire-cny2020",
            "lambo_tire-knight_premium","lambo_tire-kobra_premium","lambo_tire-nikita",
            "lambo_tire-vip_small","lambo_tire-xmas2018",
        },
    },
    ["moonlander"] = {
        paints = {
            "icecream","moonlander_hue_black-blue","moonlander_hue_blue",
            "moonlander_tractor","black-green","lights","moonlander_simple","green",
            "moonlander_hue_red","moonlander_lights","moonlander_lunar_premium",
            "moonlander_moonrabbit_premium","moonlander_nautilus_premium","saucer","VIP",
        },
        wheels = {
            "moonlander_default","moonlander_lights","moonlander_simple",
            "moonlander_tractor","moonlander_tire-lunar_premium",
            "moonlander_tire-moonrabbit_premium","moonlander_tire-nautilus_premium",
            "moonlander_tire-vip",
        },
    },
    ["rockbouncer"] = {
        paints = {
            "rockbouncer_blue_common","rockbouncer_orange_common","rockbouncer_red_common",
            "rockbouncer_violet_common","rockbouncer_yellow_common","rockbouncer_purple_rare",
            "rockbouncer_grunge_epic","rockbouncer_grunge_red_epic","rockbouncer_leopard_epic",
            "rockbouncer_yellowblue_epic","rockbounder_leopard_purple_epic",
            "rockbouncer_blue17_premium","rockbouncer_christmas24_premium",
            "rockbouncer_cny2024_premium","rockbouncer_green_premium",
            "rockbouncer_purple12_premium","rockbouncer_rough_premium",
            "rockbouncer_strawberry_premium","VIP",
        },
        wheels = {
            "rockbouncer_tire-common","rockbouncer_tire-rare","rockbouncer_tire-grunge-red_epic",
            "rockbouncer_tire-grunge_epic","rockbouncer_default",
            "rockbouncer_tire-blue17_premium","rockbouncer_tire-christmas24_premium",
            "rockbouncer_tire-cny2024_premium","rockbouncer_tire-green_premium",
            "rockbouncer_tire-purple12_premium","rockbouncer_tire-rough_premium",
            "rockbouncer_tire-strawberry_premium","rockbouncer_tire-vip_big",
        },
    },
    ["hoverbike"] = {
        paints = {
            "hoverbike_blue_common","hoverbike_brown_common","hoverbike_green_common",
            "hoverbike_purple_common","hoverbike_red_common","hoverbike_teal_common",
            "hoverbike_greenblue_rare","hoverbike_pinkblue_rare","hoverbike_purplegray_rare",
            "hoverbike_digital_epic","hoverbike_grid_epic","hoverbike_stars_epic",
            "fusell_premium","hoverbike_drakkar_premium","hoverbike_halloween2024_premium",
            "hoverbike_ironclad_premium","hoverbike_moooo_premium",
            "hoverbike_scifi_premium","VIP",
        },
        wheels = {},
    },
    ["raider"] = {
        paints = {
            "raider_blue_common","raider_green_common","raider_pink_common",
            "raider_purple_common","raider_yellow_common","raider_geometric_pink_rare",
            "raider_geometric_red_rare","raider_geometric_yellow_rare","raider_orange_rare",
            "raider_red_rare","raider_hexagon_epic","raider_mech_green_epic",
            "raider_mech_white_epic","raider_cheese_premium","raider_cny2025_premium",
            "raider_fish_premium","raider_gold_premium","raider_hazardeer_premium",
            "raider_spirit_premium","VIP",
        },
        wheels = {
            "raider_tire-dark_common","raider_tire-decorative_common","raider_tire-star_common",
            "raider_tire-geometric_pink_rare","raider_tire-geometric_red_rare",
            "raider_tire-geometric_yellow_rare","raider_tire-orange_rare","raider_tire-hex_epic",
            "raider_tire-mech_green_epic","raider_tire-mech_white_epic",
            "raider_tire-cheese_premium","raider_tire-cny2025_premium","raider_tire-default",
            "raider_tire-fish_premium","raider_tire-gold_premium",
            "raider_tire-hazardeer_premium","raider_tire-spirit_premium",
            "raider_tire-vip_premium",
        },
    },
    ["glider"] = {
        paints = {
            "glider_blue_common","glider_gray_common","glider_green_common",
            "glider_purple_common","glider_red_common","glider_yellow_common",
            "glider_bent_blue_rare","glider_bent_burgundy_rare","glider_bent_mint_rare",
            "glider_colorful_rare","glider_star_rare","glider_wooden_rare",
            "glider_rebel_epic","glider_requisitioned_epic","glider_christmas25_premium",
            "glider_cyber_premium","glider_magic_premium","glider_rustbucket_premium",
            "glider_wasp_premium","VIP",
        },
        wheels = {
            "glider_tire-common","glider_tire-bent_blue_rare","glider_tire-bent_burgundy_rare",
            "glider_tire-bent_mint_rare","glider_tire-colorful_rare","glider_tire-star_rare",
            "glider_tire-wooden_rare","glider_tire-rebel_epic","glider_tire-requisitioned_epic",
            "glider_default","glider_tire-christmas25_premium","glider_tire-cyber_premium",
            "glider_tire-magic-premium","glider_tire-rustbucket_premium","glider_tire-vip",
            "glider_tire-wasp_premium",
        },
    },
    ["trusty"] = {
        paints = {
            "trusty_blue_common","trusty_green_common","trusty_red_common",
            "trusty_blue_rare","trusty_green_rare","trusty_yellow_rare","trusty_pop_epic",
            "trusty_purple_epic","trusty_phantom_premium","trusty_pinata2025_premium",
            "trusty_dirt_premium","VIP",
        },
        wheels = {
            "trusty_default","trusty_default2","trusty_tire-phantom_premium",
            "trusty_tire-pinata2025_premium","trusty_tire-vip",
            "trusty_wheel-inferno_premium","trusty_tire-dirt_premium",
        },
    },
    ["atv"] = {
        paints = {
            "atv_red_common","atv_sport-blue_common","atv_yellow_common","atv_mint_rare",
            "atv_royale_rare","atv_sport-gerbera_rare","atv_sport-keke_rare","atv_camo_epic",
            "atv_circuit_epic","atv_circus_epic","atv_moo_epic","atv_sport-flame_epic",
            "atv_sport-flameblue_epic","atv_futuristic_premium","atv_greek_premium",
            "atv_halloween25_mythic","atv_shark_premium","VIP",
        },
        wheels = {
            "atv_tire-road_common","atv_tire-camo_epic","atv_tire-circuit_epic",
            "atv_default","atv_tire-futuristic_premium","atv_tire-greek_premium",
            "atv_tire-halloween25_mythic","atv_tire-shark_premium","atv_tire-VIP",
        },
    },
    ["super_offroad"] = {
        paints = {
            "super_offroad_blue_common","super_offroad_purple_common",
            "super_offroad_red_common","super_offroad_white_common",
            "super_offroad_camo_brown_rare","super_offroad_camo_green_rare",
            "super_offroad_tendril_green_rare","super_offroad_tendril_purple_rare",
            "super_offroad_beeple_epic","super_offroad_beeple_yellow_epic",
            "super_offroad_magenta_epic","super_offroad_cny26_premium",
            "super_offroad_beeple_pop_premium","super_offroad_tactical_blue_premium",
            "super_offroad_tactical_green_premium","VIP",
        },
        wheels = {
            "super_offroad_tire-cny26_premium","super_offroad_tire-roller",
            "super_offroad_tire-roller_rusty","super_offroad_tire-gear",
            "super_offroad_tire-gear_grimy","super_offroad_default",
            "super_offroad_tire-tactical_blue_premium",
            "super_offroad_tire-tactical_green_premium","super_offroad_tire-vip",
        },
    },
    ["stock"] = {
        paints = {
            "stocker_red_common","stocker_purple_common","stocker_green_common",
            "stocker_orange_common","stocker_blue_common","stocker_bluestar_rare",
            "stocker_darkstar_rare","stocker_darkstripe_rare","stocker_whitestripe_rare",
            "stock_wave_epic","stock_circuit-orange_epic","stock_circuit-green_epic",
            "stock_abstract_epic","stock_6-7_premium","stock_drak_premium",
            "stock_flame_mythic","VIP",
        },
        wheels = {
            "stock_default","stock_tire-circuit-green_epic","stock_tire-circuit-orange_epic",
            "stock_tire-wave_epic","stock_tire-abstract_epic","stock_tire-6-7-premium",
            "stock_tire-drak_premium","stock_tire-flame_mythic","stock_tire-vip",
        },
    },
    ["rocketkart"] = {
        paints = {
            "rocketkart_red_common","rocketkart_gray_common","rocketkart_green_common",
            "rocketkart_yellow_common","rocketkart_blue_common","rocketkart_curves_rare",
            "rocketkart_darkburst_rare","rocketkart_speckled_rare","rocketkart_starburst_rare",
            "rocketkart_swirls_rare","rocketkart_swoop_rare","rocketkart_crimson_epic",
            "rocketkart_greenblack_epic","rocketkart_orchid_epic","rocketkart_synth_epic","VIP",
        },
        wheels = {
            "rocketkart_tire-rare","rocketkart_tire-crimson_epic",
            "rocketkart_tire-greenblack_epic","rocketkart_tire-orchid_epic",
            "rocketkart_tire-synth_epic","rocketkart_tire-vip",
        },
    },
}
